name: JustFly
version: 1.0

main: io.github.radcraftplay.justfly.JustFly

commands:
  fly:
    description: Allows player to fly
    usage: "Usage: /fly [player]"

permissions:
  justfly.*:
    description: Gives access to all JustFly commands
    children:
      justfly.fly: true
      justfly.flyothers: true
  justfly.fly:
    description: Lets player enable/disable fly for themselves
  justfly.flyothers:
    description: Lets player enable/disable fly for other players